### PR TITLE
Fix compression parameter to compress in Judges::Push#run for BazaRb.new

### LINKED ISSUE #127: Wrong parameter compression in Judges::Push#run for BazaRb.new
See https://github.com/yegor256/judges/blob/0.26.0/lib/judges/commands/push.rb#L56
Must be `compress` - https://github.com/zerocracy/baza.rb/blob/0.0.8/lib/baza-rb.rb#L61
Related https://github.com/zerocracy/judges-action/pull/318#issuecomment-2325235773

### PR DESCRIPTION
**Pull request by Yegorov**
Closes #127

### CODE REVIEW

**Review by Suban05 — APPROVED** [review]
@Yegorov 👍

**Comment by Yegorov** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor release, tag is `0.26.1`

**Comment by 0crat** [comment]
@Suban05 Hey there! 👋 Thanks for your review! You've earned +4 points, which breaks down like this: +4 base points, -10 for having only 2 comments (policy suggests at least 6), and +10 to keep you motivated. While more comments could've boosted your score (up to 8 points!), we appreciate your effort. Remember, even reviewing your own code can earn points! Your current balance is [+387](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Keep up the good work and aim for more detailed reviews next time! 💪

**Pull request merged**
