### PR TITLE
valve

### PR DESCRIPTION
**Pull request by yegor256**
#136

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256 Hey there! 👋 Great job on your contribution! You've earned +4 points for this one. Here's the breakdown: +4 base points, +5 for your 105 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html), -16 for no code review (oops!), and +11 to keep you motivated. Remember, code reviews are crucial – they could've boosted your points and improved your code quality. Keep the contributions coming, but try to get them reviewed next time! Your current balance is [-160](https://zerocracy.github.io/judges-action/zerocracy-vitals.html). Let's work on improving that, shall we? 💪 [Keep up](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the good work!

**Pull request merged**
